version: '2.2'
services:
  app:
    container_name: contenedor_python
    image: juanantpineda/publicaciones:${VERSION}
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DJ_USER: ${DJ_USER}
      DJ_PASSWORD: ${DJ_PASSWORD}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DJ_EMAIL: ${DJ_EMAIL}
      URL: ${URL}
    ports:
      - ${PORT}:3000
    depends_on:
      - db
  db:
    container_name: servidor_mysql1
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb_data1:/var/lib/mysql
volumes:
    mariadb_data1:
