version: '2.2'
services:
  app:
    container_name: contenedor_python
    image: juanantpineda/publicaciones:v1
    restart: always
    environment:
      DB_NAME: django
      DB_USER: django
      DB_PASSWORD: django
      DB_HOST: servidor_mysql1
      DJ_USER: django
      DJ_PASSWORD: django
    ports:
      - 8086:3000
    depends_on:
      - db
  db:
    container_name: servidor_mysql1
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      MYSQL_ROOT_PASSWORD: asdasd
    volumes:
      - mariadb_data1:/var/lib/mysql
volumes:
    mariadb_data1:
